[General]
Application.check_updates=False
Application.completed_tutorial_steps=SourceMessagesProcessed
Application.eyecandy_gradient=ColorfulPeach
Application.font_header_family=Noto Sans
Application.font_main_family=Noto Sans Mono Medium
Application.hide_completed=False
Application.last_selected_backlog=ec4c7119-e1fb-4a9f-9cca-0d3b7f868df9
Application.last_version=1.0.2
Application.quit_on_close=True
Application.shortcuts="{\"application.settings\": \"F10\", \"application.quit\": \"Ctrl+Q\", \"application.import\": \"Ctrl+I\", \"application.export\": \"Ctrl+E\", \"application.about\": \"\", \"application.toolbar\": \"\", \"application.stats\": \"F9\", \"application.workSummary\": \"F3\", \"application.contactGithub\": \"\", \"application.contactDiscord\": \"\", \"application.contactReddit\": \"\", \"application.contactLinkedIn\": \"\", \"application.contactTelegram\": \"\", \"application.contactEmail\": \"\", \"backlogs_table.newBacklog\": \"Ctrl+N\", \"backlogs_table.newBacklogFromIncomplete\": \"Ctrl+M\", \"backlogs_table.renameBacklog\": \"Ctrl+R\", \"backlogs_table.deleteBacklog\": \"F8\", \"backlogs_table.dumpBacklog\": \"Ctrl+D\", \"workitems_table.newItem\": \"Ins\", \"workitems_table.renameItem\": \"F6\", \"workitems_table.deleteItem\": \"Del\", \"workitems_table.startItem\": \"Ctrl+S\", \"workitems_table.completeItem\": \"Ctrl+P\", \"workitems_table.addPomodoro\": \"Ctrl++\", \"workitems_table.removePomodoro\": \"Ctrl+-\", \"workitems_table.hideCompleted\": \"\", \"focus.voidPomodoro\": \"Ctrl+V\", \"focus.interruption\": \"Ctrl+T\", \"focus.finishTracking\": \"Ctrl+S\", \"focus.nextPomodoro\": \"\", \"focus.completeItem\": \"\", \"window.focusMode\": \"\", \"window.showMainWindow\": \"\", \"window.showSearch\": \"Ctrl+F\", \"window.showBacklogs\": \"Ctrl+B\", \"window.showUsers\": \"Ctrl+T\"}"
Application.show_tutorial=False
Application.table_row_height=25
Application.theme=dark
Application.window_height=756
Application.window_width=1266
Pomodoro.default_rest_duration=600
Pomodoro.default_work_duration=2700
Pomodoro.long_break_each=6
